/* Utility Platform — central tool catalog.
   Add each new live tool here once. Higher addedOrder = newer.
   Homepage and tools/ use this single registry for cards, search, and category counts. */
window.UTILITY_TOOLS = [
  {slug:"aspect-ratio",title:"Aspect Ratio Calculator",href:"aspect-ratio-calculator/",category:"digital-developer",description:"Calculate image and video aspect ratios, find missing dimensions, and resize content without changing proportions.",addedOrder:20,keywords:["aspect ratio calculator","aspect ratio","image aspect ratio calculator","video aspect ratio calculator","aspect ratio finder","aspect ratio checker","16:9 calculator","aspect ratio converter","image ratio calculator","width height ratio calculator","resize image proportionally","image dimensions calculator"]},
  {slug:"business-hours",title:"Business Hours Calculator",href:"business-hours-calculator/",category:"math-science",description:"Calculate working hours between dates with custom schedules and holidays, or add and subtract business hours to find a work-time deadline.",addedOrder:19,keywords:["business hours calculator","business hours between dates","working hours between dates","working hours calculator","calculate business hours","business time calculator","business hours elapsed","work hours between dates","billable hours between dates","SLA business hours calculator","business deadline calculator","add business hours","subtract business hours","working time between timestamps","business days hours calculator"]},
  {slug:"paver-edge-restraint",title:"Paver Edge Restraint Calculator",href:"paver-edge-restraint-calculator/",category:"home-construction",description:"Calculate open paver edge restraint, edging sections, straight and curved spikes, waste and optional material cost.",addedOrder:18,keywords:["paver edge restraint calculator","paver edging calculator","paver edging calculator linear feet","paver edge restraint length calculator","paver edging sections calculator","how much paver edging do I need","paver edging material calculator","paver edging spike calculator","paver edge restraint spike calculator","patio edging calculator","paver patio edging calculator","walkway edging calculator","paver border edging calculator","paver restraint calculator","paver edging quantity calculator"]},
  {slug:"deck-joist-blocking",title:"Deck Joist Blocking Calculator",href:"deck-joist-blocking-calculator/",category:"home-construction",description:"Calculate joist blocking pieces, cut length, required lumber, stock boards, waste and optional fasteners for deck or floor framing layouts.",addedOrder:17,keywords:["deck joist blocking calculator","joist blocking calculator","deck blocking calculator","floor joist blocking calculator","blocking quantity calculator","joist blocking quantity","blocking lumber calculator","how many joist blocks","deck blocking spacing","joist blocking material calculator"]},
  {slug:"sod-staple",title:"Sod Staple Calculator",href:"sod-staple-calculator/",category:"home-construction",description:"Estimate sod staples, landscape pins and turf staples from area, spacing, edges, seams and package size.",addedOrder:16,keywords:["sod staple calculator","sod staples","sod pins","landscape staples","turf staples","how many sod staples","sod staple spacing","sod pins calculator","landscape staple calculator","sod staple quantity"]},
  {slug:"find-replace",title:"Find and Replace Text Online",href:"find-replace/",category:"digital-developer",description:"Find and replace repeated text with case, whole-word, replace-all and replace-first controls.",addedOrder:15,keywords:["find and replace","find replace","replace text","text replace","search and replace","replace all","find and replace text online","replace words in text","bulk text replace"]},
  {slug:"word-counter",title:"Word Counter & Character Counter",href:"word-counter/",category:"digital-developer",description:"Count words, characters, sentences, paragraphs and lines, with reading time and a live character-limit checker.",addedOrder:14,keywords:["word counter","character counter","word count","character count","char count","letter count","sentence count","paragraph count","reading time","character limit","word counter online","character counter online"]},
  {slug:"case-converter",title:"Case Converter Online",href:"case-converter/",category:"digital-developer",description:"Convert text to uppercase, lowercase, title, sentence, camelCase, PascalCase, snake_case, kebab-case and CONSTANT_CASE.",addedOrder:13,keywords:["case converter","uppercase","lowercase","title case","sentence case","camelCase","PascalCase","snake case","kebab case","constant case","text case converter","uppercase lowercase converter"]},
  {slug:"remove-line-breaks",title:"Remove Line Breaks Online",href:"remove-line-breaks/",category:"digital-developer",description:"Join wrapped lines, preserve paragraphs, or replace line breaks with spaces and custom separators.",addedOrder:12,keywords:["remove line breaks","line break remover","remove newlines","line breaks","newline remover","unwrap text","pdf line breaks","remove line breaks online","join lines","remove paragraph breaks"]},
  {slug:"duplicate-line-remover",title:"Duplicate Line Remover",href:"duplicate-line-remover/",category:"digital-developer",description:"Remove repeated lines while preserving order, with options for case, whitespace, blank lines and which occurrence to keep.",addedOrder:11,keywords:["duplicate line remover","remove duplicate lines","duplicate lines","deduplicate text","dedupe list","unique lines","remove repeats","duplicate remover online","remove duplicate rows"]},
  {slug:"text-cleaner",title:"Text Cleaner Online",href:"text-cleaner/",category:"digital-developer",description:"Clean messy text by trimming lines, removing extra spaces, blank lines and duplicate lines, and normalizing line breaks.",addedOrder:10,keywords:["text cleaner","clean text","text formatter","remove extra spaces","remove blank lines","remove duplicate lines","line breaks","whitespace","online text cleaner","clean up text"]},
  {slug:"conduit-fill",title:"Conduit Fill Calculator",href:"conduit-fill-calculator/",category:"energy-electrical",description:"Check raceway fill for mixed conductors and find the smallest practical conduit size.",addedOrder:8,keywords:["conduit fill calculator","electrical conduit fill calculator","conduit fill calculation","raceway fill calculator","electrical conduit calculator","EMT conduit fill calculator","PVC conduit fill calculator","conduit fill percentage calculator","wire conduit fill calculator","NEC conduit fill calculator","conduit size calculator","conduit fill capacity"]},
  {slug:"wire-size",title:"Wire Size & Voltage Drop Calculator",href:"wire-size-calculator/",category:"energy-electrical",description:"Plan cable size from load, voltage, distance, material and voltage-drop target.",addedOrder:7,keywords:["wire size calculator","wire size and voltage drop calculator","electrical wire size calculator","cable size calculator","voltage drop calculator","wire gauge calculator","AWG wire size calculator","cable voltage drop calculator","DC wire size calculator","solar cable size calculator","inverter cable size calculator","voltage drop wire calculator"]},
  {slug:"paint",title:"Paint Calculator",href:"paint-calculator/",category:"home-construction",description:"Estimate paint needed for walls and ceilings, subtract openings, choose coats and coverage, and convert gallons and litres.",addedOrder:9,keywords:["paint calculator","paint quantity calculator","how much paint do I need","wall paint calculator","ceiling paint calculator","paint coverage calculator","gallon paint calculator","litre paint calculator","paint estimator","room paint calculator"]},
  {slug:"fence",title:"Fence Material Calculator",href:"fence-calculator/",category:"home-construction",description:"Estimate posts, rails, pickets or panels, concrete and optional material cost.",addedOrder:6,keywords:["fence calculator","fence material calculator","fence post calculator","fence panel calculator","fence picket calculator","fence rail calculator","how many fence posts","fence cost calculator","fence materials estimator"]},
  {slug:"gravel",title:"Gravel Quantity & Ordering Planner",href:"gravel-calculator/",category:"home-construction",description:"Estimate gravel volume, approximate weight, bags and optional project cost.",addedOrder:5,keywords:["gravel calculator","gravel quantity calculator","gravel volume calculator","gravel weight calculator","gravel tons calculator","gravel cubic yard calculator","gravel ordering calculator","how much gravel do I need","aggregate calculator","stone calculator"]},
  {slug:"uuid",title:"UUID Generator & Validator",href:"uuid-generator-calculator/",category:"digital-developer",description:"Generate UUIDs, validate values and inspect version and variant information.",addedOrder:4,keywords:["UUID generator","UUID validator","UUID generator and validator","UUID v4 generator","UUID v7 generator","GUID generator","unique ID generator","UUID checker","UUID validation","bulk UUID generator"]},
  {slug:"pilot-hole",title:"Pilot Hole Size Calculator",href:"pilot-hole-calculator/",category:"home-construction",description:"Find practical pilot, clearance and countersink drill-bit starting sizes.",addedOrder:3,keywords:["pilot hole calculator","pilot hole size calculator","wood screw drill bit size","pilot hole size chart","screw pilot hole calculator","clearance hole calculator","countersink size calculator","wood screw pilot hole","drill bit size for wood screws","pilot drill bit size"]},
  {slug:"time",title:"Time Calculator",href:"time-calculator/",category:"math-science",description:"Add and subtract hours, minutes and seconds, or find the time between values.",addedOrder:2,keywords:["time calculator","time duration calculator","hours minutes seconds calculator","time difference calculator","time between two times","add time calculator","subtract time calculator","elapsed time calculator","hours calculator","duration calculator"]},
  {slug:"significant-figures",title:"Significant Figures Calculator",href:"calculator/",category:"math-science",description:"Calculate with significant figures and control precision without losing useful context.",addedOrder:1,keywords:["significant figures calculator","sig figs calculator","significant figures","sig fig calculator","significant figures rounding calculator","significant figures multiplication","significant figures division","precision calculator","rounding significant figures"]}
];

window.UTILITY_CATEGORIES = [
  {id:"math-science",title:"Math & Science",description:"Calculators for precision, measurements, scientific and everyday math.",icon:"∑",href:"math-science/"},
  {id:"home-construction",title:"Home & Construction",description:"Material, measuring, estimating and project-planning utilities.",icon:"⌂",href:"home-construction/"},
  {id:"energy-electrical",title:"Energy & Electrical",description:"Wire sizing, voltage drop, conduit fill and practical circuit planning.",icon:"ϟ",href:"energy-electrical/"},
  {id:"digital-developer",title:"Digital & Developer",description:"Identifiers, formats and practical developer workflow utilities.",icon:"<>",href:"digital-developer/"},
  {id:"finance",title:"Finance",description:"Financial planning and money utilities as the platform expands.",icon:"$"},
  {id:"converters",title:"Converters",description:"Unit and format conversion tools for common real-world tasks.",icon:"↔"}
];
